services:
  api:
    build: ./backend
    container_name: pyq_api
    volumes:
      - ./backend:/app
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  postgres:
    image: postgres:15-alpine
    container_name: pyq_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-pyqdb}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pyq_pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${POSTGRES_USER:-user}@email.com
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD:-password}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    depends_on:
      - postgres
    volumes:
    - pgadmin_data:/var/lib/pgadmin

  redis:
    image: redis:7-alpine
    container_name: pyq_redis
    ports:
      - "6379:6379"

  worker:
    build: ./backend
    container_name: pyq_worker
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    command: arq app.workers.arq_worker.WorkerSettings

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: pyq_frontend
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  postgres_data:
  pgadmin_data:
