"""add selected_resource_ids to chat_sessions

Revision ID: 983ad2983d5c
Revises: d3dcf6b6fe3f
Create Date: 2026-05-18 20:55:14.773697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '983ad2983d5c'
down_revision: Union[str, Sequence[str], None] = 'd3dcf6b6fe3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('selected_resource_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'selected_resource_ids')
    # ### end Alembic commands ###
