"""add question_pdf_url to paper_outputs

Revision ID: ab47c0990b86
Revises: 983ad2983d5c
Create Date: 2026-05-18 21:35:55.165368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab47c0990b86'
down_revision: Union[str, Sequence[str], None] = '983ad2983d5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper_outputs', sa.Column('question_pdf_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper_outputs', 'question_pdf_url')
    # ### end Alembic commands ###
