"""add chat sessions and processing progress

Revision ID: d3dcf6b6fe3f
Revises: 9f2c76932a93
Create Date: 2026-05-17 16:07:40.708352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3dcf6b6fe3f'
down_revision: Union[str, Sequence[str], None] = '9f2c76932a93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('questions', sa.Column('session_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'questions', 'chat_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.add_column('resources', sa.Column('processing_progress', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resources', 'processing_progress')
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'session_id')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
